name       : scanmem
version    : 0.15.8
release    : 1
source     :
    - https://github.com/scanmem/scanmem/archive/v0.15.8.tar.gz : 6615444932549b5baae056acdb09b2e5a6c588247b6139f47dc69f0b6c6a3e58
license    : GPL-3.0
component  : system.utils
summary    : scanmem is a debugging utility designed to isolate the address of an arbitrary variable in an executing process.
description: |
    scanmem is a debugging utility designed to isolate the address of an arbitrary variable in an executing process. scanmem simply needs to be told the pid of the process and the value of the variable at several different times.

    After several scans of the process, scanmem isolates the position of the variable and allows you to modify its value.
libsplit: no
builddeps:
    - pkgconfig(gtk+-3.0)
    - libtool
rundeps:
    - python-gobject
setup      : |
    %autogen --disable-static --enable-gui
build      : |
    %make
install    : |
    %make_install
