name       : scanmem
version    : '0.17'
release    : 5
source     :
    - https://github.com/scanmem/scanmem/archive/v0.17.tar.gz : f02054b91322cf41517506158fcb74554e9fc6644e696f8aa25e5acf162d374b
license    : GPL-3.0-or-later
component  : system.utils
summary    : scanmem is a debugging utility designed to isolate the address of an arbitrary variable in an executing process.
description: |
    scanmem is a debugging utility designed to isolate the address of an arbitrary variable in an executing process. scanmem simply needs to be told the pid of the process and the value of the variable at several different times.
libsplit   : no
builddeps  :
    - pkgconfig(gtk+-3.0)
    - libtool
rundeps    :
    - python-gobject
setup      : |
    %autogen --disable-static --enable-gui
build      : |
    %make
install    : |
    %make_install
